language: python

python:
  - "2.7"

install:
  - sudo apt-get install automake
  - cd deps/spatialindex-src-1.8.5/
  - ./configure
  - make
  - sudo make install
  - "pip install -r requirements.txt"

script:
  - py.test tests
